[workspace]
resolver = "2"

members = [
	"crates/edoras_server",
	"crates/hello", 
]

[workspace.dependencies]
anyhow = "1.0.*"
futures = "0.3.*"

[workspace.dependencies.async-std]
version = "1.12.*"
features = ["attributes"]

[workspace.dependencies.edoras_core]
path = "crates/edoras_core"
